# Full example of using requests Oauth2 flow to access TD Ameritrade API with
# registered credentials stored in environment variables.  This example is intended for
# use after requestsAPI_tddemo.py

import os
import dotenv
import json
import requests
import time
import threading

import pandas as pd

# import requests_oauthlib


from dataclasses import dataclass, field
from dotenv import load_dotenv
from urllib.parse import unquote
from threading import Timer


# from requests_oauthlib import OAuth2Session


# Repeating timer from this link: https://stackoverflow.com/questions/474528/what-is-the-best-way-to-repeatedly-execute-a-function-every-x-seconds/25251804#25251804
class RepeatedTimer(object):
    def __init__(self, interval, function, *args, **kwargs):
        self._timer = None
        self.interval = interval
        self.function = function
        self.args = args
        self.kwargs = kwargs
        self.is_running = False
        self.start()

    def _run(self):
        self.is_running = False
        self.start()
        self.function(*self.args, **self.kwargs)

    def start(self):
        if not self.is_running:
            self._timer = Timer(self.interval, self._run)
            self._timer.start()
            self.is_running = True

    def stop(self):
        self._timer.cancel()
        self.is_running = False


# A dataclass (Python 3.7+) to hold the configuration.  Normally we'd move this to
# a separate file.  Note that the __init__ method generated by @dataclass decorator
# will require any parameter not initialized with a default value be provided when
# creating an instance of the class.
#
# ref: https://docs.python.org/3/library/dataclasses.html
@dataclass
class Credentials:
    clientKey: str = None
    returnURL: str = None
    authCode: str = None
    accessToken: str = None
    refreshToken: str = None
    refreshExpire: int = None


# Utility function to url-decode the provided param.
def urlDecode(_url):
    decode = unquote(_url)
    return decode


# A regular class to manage the connection at least.
class TDAPI:
    def __init__(self):
        self.credentials = Credentials()

    # Load basic client environment settings from environment.
    def loadClientEnv(self):
        self.credentials.clientKey = os.getenv("TD_CLIENTKEY")
        self.credentials.returnURL = os.getenv("TD_RETURNURL")

        # won't have this, or won't be stored in the env soon, but see what's there.
        self.credentials.authCode = os.getenv("TD_CODE")
        self.credentials.accessToken = os.getenv("TD_ACCESSTOKEN")
        self.credentials.refreshToken = os.getenv("TD_REFRESHTOKEN")
        self.credentials.refreshExpire = os.getenv("TD_REFRESHEXPIRE")

        return self.credentials

    # Use loaded credentials to generate and return TD auth URL for use in auth grant flow.  You
    # need an auth URL before you can get an access token.
    def getAuthURL(self):
        tdAuthURL = 'https://auth.tdameritrade.com/auth'
        tdAuthParams = {
            'response_type': 'code',
            'redirect_uri': self.credentials.returnURL,
            'client_id': self.credentials.clientKey + '@AMER.OAUTHAP'
        }

        # Form the request URL.  Just pass params as dictionary and they will be encoded as
        # the url params.
        r = requests.get(tdAuthURL, params=tdAuthParams)
        return r

    # Use previously retrieved auth code to get access and refresh tokens.  Some of the following
    # added from source of tdameritrade python API available at:    
    #  https://github.com/timkpaine/tdameritrade/blob/master/tdameritrade/auth/__init__.py
    def getAccessToken(self):
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        params = {
            'grant_type': 'authorization_code',
            'refresh_token': '',
            'access_type': 'offline',
            'code': urlDecode(self.credentials.authCode),
            'client_id': self.credentials.clientKey,
            'redirect_uri': self.credentials.returnURL
        }

        authRequest = requests.post('https://api.tdameritrade.com/v1/oauth2/token', headers=headers, data=params)
        return authRequest

    # Use refresh token to get a new access token, store in environment and persist.
    def refreshAccessToken(self):
        headers = {'Content-Type': 'application/x-www-form-urlencoded'}
        params = {
            'grant_type': 'refresh_token',
            'refresh_token': self.credentials.refreshToken,
            'client_id': self.credentials.clientKey + '@AMER.OAUTHAP'
        }
        url = 'https://api.tdameritrade.com/v1/oauth2/token'
        authRequest = requests.post(url, headers=headers, data=params)

        # Store the new access token in the environment variable.
        # Need to learn how to get "access_token" field of json response.
        if authRequest.status_code == 200:
            jsonData = authRequest.json()
            self.credentials.accessToken = jsonData['access_token']
            os.environ["TD_ACCESSTOKEN"] = self.credentials.accessToken
            dotenv.set_key('.env', "TD_ACCESSTOKEN", self.credentials.accessToken)

        return authRequest

    # Sample get quote w/authentication.  
    # Set auth header to container bearer token.
    def getQuote(self, symbol):
        url = 'https://api.tdameritrade.com/v1/marketdata/quotes'
        headers = {'Authorization': 'Bearer ' + self.credentials.accessToken}
        params = {'symbol': symbol.upper()}
        request = requests.get(url, headers=headers, params=params)
        return request

    # Sample get quote w/authentication.  
    # Set auth header to container bearer token.
    def getQuotes(self, symbols):

        if type(symbols) is list:
            symbolString = ",".join((f"{s.upper()}" for s in symbols))
        else:
            symbolString = symbols

        url = 'https://api.tdameritrade.com/v1/marketdata/quotes'
        headers = {'Authorization': 'Bearer ' + self.credentials.accessToken}
        params = {'symbol': symbolString}
        request = requests.get(url, headers=headers, params=params)
        return request

    # Test getting price history.  Also figure out pandas, what a dataframe is, and
    # best way to convert times.  Appears that pandas can convert the msec to a 
    # datetime also.  pandas is a data analysis library.
    # periodType:       day (default), month, year, ytd
    # period:           number of periods to show (5 days, etc)
    # frequencyType:    minute, daily, weekly, monthly
    # frequency:        count of frequencyType to be included in each candle (5 minutes, etc)
    # endDate:          end date as milliseconds since epoch.  If start/end provided, period shouldn't be.
    # startDate:        start date as milliseconds since epoch.
    # extended:         needExtendedHoursData -- true to return extend hours (default)
    #
    def getPriceHistory(self, symbol, **kwargs):
        url = 'https://api.tdameritrade.com/v1/marketdata/' + symbol.upper() + '/pricehistory'
        headers = {'Authorization': 'Bearer ' + self.credentials.accessToken}

        params = {
            'periodType': 'day',
            'period': 2,
            'frequencyType': 'minute',
            'frequency': 30
        }
        request = requests.get(url, headers=headers, params=kwargs)
        return request

    # Get quote.  Refresh token if needed.
    def quoteWithRefresh(self, symbol, **kwargs):

        try:
            r = self.getQuotes(symbol)

            if r.status_code == 401:
                self.refreshAccessToken()
                r = self.getQuotes(symbol)

        except Exception as e:
            print(f"Quote API Exception: ({type(e)}), {e}")
            r = None

        finally:
            return r


# timer/thread functions

# if we're running this as 'main', do some initialization.
def main():
    print('requestsAPI_tddemo: main()')
    load_dotenv()

    # Create API object and load crdentials.  If no auth token, try to use credentials to get one
    # (this isn't fully implemented).  If auth token present, use refresh token to update it.
    api = TDAPI()
    api.loadClientEnv()

    # If new token is needed (ex: refresh is expired), follow instructions in TD notes to get new access and refresh tokens. 
    # Use this to decode in order to avoid having to trust an online deoder with very secret information.
    if False:
        url = urlDecode("")
        print(url)

    # If we just retrieved an auth URL, it has to be externally authorized by pasting into a
    # browser (ctrl-click doesn't work here).  For now we assume this is already done and
    # skip it.
    if False:
        authRequest = api.getAuthURL()
        print('Request URL: ' + authRequest.url)
        print('Status: ' + repr(authRequest.status_code))
        # print('Response: ' + authRequest.)

    # Get access token if needed.  It usually is, but generally we can use the refresh token
    # to get one.  Would be nice to check the expirations and just auto-request if needed,
    # but this isn't done yet.
    if False:
        authRequest = api.getAccessToken()
        print(authRequest.status_code)
        print(authRequest.text)

    # Try to use refresh token to get a new access token:
    # Don't need this in general as getQuote call will attempt to use refresh token to get new 
    # access token if the existing one doesn't work.
    if False:
        print('Using refresh token to request new access token: ')
        authRequest = api.refreshAccessToken()
        print('Request URL:' + authRequest.url)
        print('Status: ' + repr(authRequest.status_code))
        print(authRequest.text)

    # r = api.getQuote("AAPL")
    # print (r.status_code)

    # if r.status_code == 401:
    #    api.refreshAccessToken()
    #    r = api.getQuote("AAPL")

    # if r.status_code == 200:
    #    print (r.content)

    # Now try to get a futures (e-mini) price quote
    # r = api.quoteWithRefresh("/ES")
    # if r.status_code == 200:
    #    print(r.content)

    # Set up a timer and call this once every n seconds.  For initial version just let n = 60
    # s = sched.scheduler(time.time, time.sleep)
    def updateQuote(symbols, dataFrame):

        # No problem to pass a list here but just do one for simplified printing
        r = api.quoteWithRefresh(symbols)

        if r.status_code == 200:

            # Parse the returned API data into something we actually want.
            print(r.content)
            print()

            result = json.loads(r.content)
            for q in result.items():
                # Quotes are returned as tuple with symbol in [0] and item details in [1]
                item = q[1]

                # get metadata but simplify processing because it doesn't change very often.
                # this might not need to be a dataframe -- regular dictionary would work fine here.
                # dataMeta = pd.DataFrame(q[1], columns = [
                #    'assetType', 'assetMainType', 'exchangeName', 'symbol', 'futureActiveSymbol'
                #    'tick', 'tickAmount', 'futureMultiplier', 'futureExpirationDate'
                #    # futureIsActive, futureIsTradable, delayed, realTimeEntitled
                # ])

                # next need to ensure that table is created for this but that could be easier at database level?

                # at this point we have a dictionary and we want to make a dataframe but only
                # out of certain columns
                dataAppend = pd.DataFrame(q[1], columns=[
                    'quoteTimeInLong',
                    'tradeTimeInLong',
                    'bidPriceInDouble',
                    'askPriceInDouble',
                    'openPriceInDouble',
                    'highPriceInDouble',
                    'lowPriceInDouble',
                    'closePriceInDouble',
                    'lastPriceInDouble',
                    'mark'
                    'bidSizeInLong',
                    'askSizeInLong',
                    'lastSizeInLong',
                    'totalVolume',
                    'openInterest'
                    'changeInDouble'
                ], index=[0])

                dataFrame = dataFrame.append(dataAppend, ignore_index=True)

                print(dataAppend.to_string(index=False, header=False))

                # print(f"Sytmbol: {q[0]}\n")
                # print(item)
                # print(f"{item['quoteTimeInLong']}, {item['tradeTimeInLong']}, {item['openPriceInDouble']}, {item['highPriceInDouble']}, {item['lowPriceInDouble']}, {item['closePriceInDouble']}, {item['mark']}")

        else:
            print(r.status_code)

        return dataFrame

    # fields we care asbout:
    # bidPriceInDouble, askPriceInDouble, lastPriceIndouble
    # bidSizeInLong, askSieInLong, lastSizeInLong
    # totalVolume, openInterest
    # quoteTimeInLong, tradeTimeInLong
    # openPriceInDouble, highPriceInDouble, lowPriceInDouble. closePriceInDouble
    # mark
    # description
    # delayed, realTimeEnabled (should be: 'false', 'true')
    # futureIsActive, futureIsTradeable
    # futureExpirationDate

    # Most basic way with sched:
    # s.enter(10, 1, updateQuote, (s,))
    # s.run()

    # Try using the repeated timer object.  This is ok but it does nothing to create an event loop so
    # that still needs to be done.  Might as well just run this thing in a separate thread.
    def timerAction():
        interval = 10.0
        symbols = ("/ES",)
        dataFrame = pd.DataFrame()

        while True:
            dataFrame = updateQuote(symbols, dataFrame)
            # print(dataFrame)
            time.sleep(interval)

    # Create a separate thread to run the timer task.
    threading.Thread(target=lambda: timerAction()).start()

    # Next:
    # 1) 
    # 2) Update this to run as an exe (and consider whether python is the best choice here)  Get running in linux 
    #    as a service, and create a means of communicating with the running service (similar to neuron-cli).


# Call main function *if* this is the main module.  This provides a familiar structure
# often used with many other languages.
if __name__ == '__main__':
    main()

else:
    print(__name__)

# TD API issues:
# 1) appears it is possible to stream futures price quotes and save them that way
# 2) unfortunately futures data is not supported for price history (THIS SUCKS!!!)
# 3) also futures trading is not supported by the API (THIS ALSO SUCKS!!!)
#
# > May need to buy some data for backtesting.  Check with CME.  Even buying minute data
#   would be extremely useful. 
# 
# > Streaming futures data would be useful to build a library going forward.
