#!/usr/bin/env bash
# backup_metadata.sh — dump the metadata tier of a trading database (slice 915).
#
# The metadata tables are the ones with no external source: losing them forces
# a mass re-pull from providers (this is what the 2026-08-04 incident
# destroyed). The bar data (hypertables) and derived caggs are deliberately
# NOT dumped here — they have their own tier (base backup + WAL archive).
#
# The table list is DERIVED FROM THE CATALOG at run time (D4): everything in
# schema `public` that is neither a hypertable nor a continuous aggregate. A
# hardcoded list would silently omit tables future migrations add.
#
# Usage:
#   backup_metadata.sh --db-url <url> --dest <dir>
#
# Both arguments are required (D5). This tool never reads its target from the
# environment: a dump aimed by an ambient variable is the failure mode the
# backup exists to repair.
set -euo pipefail

usage() {
  echo "usage: $0 --db-url <postgresql-url> --dest <directory>" >&2
  echo "  --db-url   database to dump (required; never read from environment)" >&2
  echo "  --dest     directory to write the dump into (required)" >&2
}

# daemon_heartbeat is runtime liveness state: regenerated by the daemon on
# startup and meaningless after a restore (a restored heartbeat would claim a
# daemon is alive that is not). Excluded deliberately, not because it happened
# to be empty on the day this was written.
EXCLUDED_RUNTIME_TABLES=("daemon_heartbeat")

DB_URL=""
DEST=""
while [ $# -gt 0 ]; do
  case "$1" in
    --db-url) DB_URL="${2:-}"; shift 2 ;;
    --dest)   DEST="${2:-}"; shift 2 ;;
    *) echo "error: unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

if [ -z "$DB_URL" ]; then
  echo "error: --db-url is required" >&2; usage; exit 2
fi
if [ -z "$DEST" ]; then
  echo "error: --dest is required" >&2; usage; exit 2
fi

# Built as `= ANY(array)` rather than NOT IN: a NULL anywhere in a NOT IN
# list makes the predicate NULL for every row, silently excluding everything.
EXCLUDE_LIST=""
for t in "${EXCLUDED_RUNTIME_TABLES[@]}"; do
  EXCLUDE_LIST="${EXCLUDE_LIST:+$EXCLUDE_LIST, }'${t}'"
done

# Everything in public that is not a hypertable and not a cagg. The cagg
# exclusion also catches the materialized view names should they ever appear
# in pg_tables; the internal chunk tables live in _timescaledb_internal and
# are excluded by the schema filter.
ENUM_SQL="
SELECT tablename FROM pg_tables
 WHERE schemaname = 'public'
   AND tablename NOT IN (SELECT hypertable_name FROM timescaledb_information.hypertables)
   AND tablename NOT IN (SELECT view_name FROM timescaledb_information.continuous_aggregates)
   AND NOT (tablename = ANY (ARRAY[${EXCLUDE_LIST}]::text[]))
 ORDER BY tablename;"

mapfile -t TABLES < <(psql "$DB_URL" -X -At -v ON_ERROR_STOP=1 -c "$ENUM_SQL")

# An empty enumeration means the target is not a trading database (or the
# query broke). Refuse rather than produce an empty dump that looks like a
# backup.
if [ "${#TABLES[@]}" -eq 0 ]; then
  echo "error: metadata enumeration returned no tables — wrong database?" >&2
  exit 1
fi

DUMP_ARGS=()
for t in "${TABLES[@]}"; do
  DUMP_ARGS+=(-t "public.\"${t}\"")
done

mkdir -p "$DEST"
OUT="$DEST/meta-$(date +%Y%m%dT%H%M%S).dump"
TMP="$OUT.part"
# A failed pg_dump must not leave a file that looks like a completed dump.
trap 'rm -f "$TMP"' EXIT

echo "dumping ${#TABLES[@]} metadata tables to $OUT"
pg_dump "$DB_URL" -Fc "${DUMP_ARGS[@]}" -f "$TMP"
mv "$TMP" "$OUT"
trap - EXIT

echo "done: $(du -h "$OUT" | cut -f1) $OUT"
